
import { Quicksand } from 'next/font/google';
import './styles/globals.css';

const quicksand = Quicksand({
    subsets: ['latin'],
    variable: '--font-quicksand',
});

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
    return (
        <html lang='en'>
            <body className={`${quicksand.variable} antialiased`}>

                {children}
            </body>
        </html>
    );
}
